# Generated by GitHub Copilot on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("phone", "Phone")], max_length=10),
                ),
                ("destination", models.CharField(max_length=255)),
                ("code_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="users.user",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["user", "channel", "destination"], name="users_verif_user_id_9ebc49_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["expires_at"], name="users_verif_expires_b76f0c_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["used_at"], name="users_verif_used_at_a043d0_idx"),
        ),
    ]
