# Generated by Django 5.2.9 on 2025-12-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyamenityrelation",
            name="amenity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.propertyamenity",
            ),
        ),
        migrations.AddField(
            model_name="propertyamenityrelation",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenity_relations",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyfavorite",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="inquirer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyreview",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "status"], name="properties__city_eb43d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "status"],
                name="properties__propert_487234_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["-created_at"], name="properties__created_9ef325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["owner"], name="properties__owner_i_9e1ae3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="propertyamenityrelation",
            unique_together={("property", "amenity")},
        ),
        migrations.AddIndex(
            model_name="propertyfavorite",
            index=models.Index(fields=["user"], name="properties__user_id_59b2b2_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyfavorite",
            index=models.Index(
                fields=["property"], name="properties__propert_4fc30d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyfavorite",
            unique_together={("user", "property")},
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["property"], name="properties__propert_63674f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["inquirer"], name="properties__inquire_60f020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(fields=["status"], name="properties__status_773da0_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyreview",
            index=models.Index(
                fields=["property"], name="properties__propert_ea8564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyreview",
            index=models.Index(
                fields=["reviewer"], name="properties__reviewe_1f1f58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyreview",
            unique_together={("property", "reviewer")},
        ),
    ]
