# Generated by Django 5.2.9 on 2026-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Neighborhood or area (e.g., Jebel, Hai Al-Matar)",
                max_length=100,
            ),
        ),
    ]
